name: Koboldcpp Builder

on:
  release:
    types:
      - created
      - edited
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install git curl bzip2

      - name: Build
        id: make_build
        run: |
          ./koboldcpp.sh dist

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./dist/*"]'